import { mkdir, mkdtemp, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { Context } from '@deepseek-ai/cordis'
import type { Agent } from '@deepseek-ai/dsh-agent'
import type { SubagentRuntime, SubagentStartRequest } from '@deepseek-ai/dsh-subagent'
import { describe, expect, it, vi } from 'vitest'
import { DynamicWorkflowService, projectPartitionKey } from '../src/service.js'
import { validateWorkflowManifest } from '../src/capsule.js'
import type { ResolvedWorkflowConfig, WorkflowRun, WorkflowRunSnapshot } from '../src/types.js'

function config(root: string): ResolvedWorkflowConfig {
  return {
    projectDirectory: join(root, 'project-workflows'), personalDirectory: join(root, 'personal-workflows'), runDirectory: join(root, 'runs'),
    maxCapsuleBytes: 100_000, maxCatalogEntries: 100, maxAgents: 16, maxConcurrency: 4,
    maxResultChars: 20_000, scriptSyncTimeoutMs: 100, scriptWallTimeoutMs: 2_000,
    defaultProvider: 'spawn', synthesisProvider: 'spawn',
    modelTiers: { fast: { subagentProvider: 'spawn', maxTokens: 10 }, balanced: { subagentProvider: 'spawn', maxTokens: 20 }, deep: { subagentProvider: 'spawn', maxTokens: 30 } },
    readOnlyToolFilter: { deny: ['write'] }, approvalMode: 'never', availableTools: [], availableMcp: [], availableSkills: [],
    maxRetainedRuns: 20, pluginVersion: '0.1.0', dshVersion: '0.0.1-rc.2',
  }
}

function agent(cwd: string): Agent {
  return { session: { id: 'parent', header: { cwd }, snapshotEvents: () => [], append: vi.fn() } } as unknown as Agent
}

function authoredPayload() {
  return {
    manifest: { name: 'generated-review', description: 'Review generated by the author.', phases: ['run'], readOnly: true, maxAgents: 2, maxConcurrency: 1, patterns: ['adversarial-verification'], inputSchema: { type: 'object', additionalProperties: true } },
    source: `async function run(wf, args) { return await wf.runAgent({ name: 'reviewer', prompt: String(args.request || 'review'), readOnly: true }); }`,
    intent: { taskClass: 'review', originalRequest: 'review this' }, inputs: { description: 'request' }, requires: {},
  }
}

function subagents() {
  let sequence = 0
  const start = vi.fn(async (_provider: string, request: SubagentStartRequest) => {
    const index = ++sequence
    const isScout = request.label === 'workflow-scout'
    const isAuthor = request.label === 'workflow-author'
    const result = isScout
      ? { output: [{ type: 'text' as const, text: 'facts' }], stopReason: 'completed' as const }
      : isAuthor
        ? { output: [{ type: 'text' as const, text: 'capsule' }], structured: authoredPayload(), stopReason: 'completed' as const }
        : { output: [{ type: 'text' as const, text: `child:${request.label ?? index}` }], stopReason: 'completed' as const }
    return { id: `child-${index}`, localAgent: undefined, result: Promise.resolve(result), dispose: vi.fn(async () => {}) }
  })
  return {
    start,
    value: { getProvider: (name: string) => name === 'spawn' ? { name, capabilities: { outputSchema: true, depthLimit: true, toolFilter: true, persona: true }, inheritsParentContext: false } : undefined, start } as unknown as SubagentRuntime,
  }
}

async function fixture() {
  const root = await mkdtemp(join(tmpdir(), 'dsh-workflow-service-'))
  const fake = subagents()
  const userQuestions = { ask: vi.fn(async () => ({ answers: [{ id: 'workflow-approval', selected: ['Run'] }] })) }
  const jobs = { start: vi.fn(input => { const control = input.run(); void control.done; return 'workflow-1' }) }
  const service = new DynamicWorkflowService(new Context(), { config: config(root), subagents: fake.value, userQuestions: userQuestions as never, jobs: jobs as never })
  return { root, fake, userQuestions, jobs, service, agent: agent(root) }
}

function completedRun(status: WorkflowRunSnapshot['status']): WorkflowRun {
  const value: WorkflowRunSnapshot = {
    runId: `run-${status}`, workflow: 'background', displayName: 'background', status, source: 'inline', execution: 'capability-generated',
    startedAt: 1, endedAt: 2, totalSpawned: 0, activeAgents: 0, eventCount: 0, artifacts: [], ...(status === 'failed' ? { error: 'failed' } : {}),
  }
  return { runId: value.runId, done: Promise.resolve(value), getSnapshot: () => value }
}

describe('dynamic workflow service', () => {
  it('uses collision-resistant project partitions', () => {
    expect(projectPartitionKey('C:\\tenant-workspaces\\ey331b-n6yzn6')).not.toBe(projectPartitionKey('C:\\tenant-workspaces\\1g8nhlj-1hral3e'))
    expect(projectPartitionKey('C:\\tenant-workspaces\\ey331b-n6yzn6')).toMatch(/^[a-f0-9]{64}$/u)
  })
  it('discovers built-ins, authors/saves/runs, and manages durable identities', async () => {
    const fx = await fixture()
    const initial = await fx.service.list(fx.agent)
    expect(initial.entries.map(item => item.name)).toEqual(expect.arrayContaining(['parallel-investigation', 'scoped-review', 'adversarial-verification']))

    const authored = await fx.service.create(fx.agent, 'review this', new AbortController().signal, { scope: 'project' })
    expect(authored.path).toMatch(/generated-review\.workflow\.json$/u)
    const savedRerun = await fx.service.rerun(fx.agent, 'generated-review', { request: 'saved' })
    expect(await savedRerun.done).toMatchObject({ status: 'completed', savedWorkflowName: 'generated-review' })
    const run = await fx.service.startNamed(fx.agent, 'generated-review', { request: 'src' })
    const completed = await run.done
    expect(completed).toMatchObject({ status: 'completed', savedWorkflowName: 'generated-review' })
    expect(fx.service.show(fx.agent, run.runId)?.resultSummary).toContain('reviewer')
    const revisedFromRun = await fx.service.revise(fx.agent, run.runId, 'tighten the review', new AbortController().signal, true)
    expect(revisedFromRun.capsule.provenance).toMatchObject({ fromRunId: run.runId, revisionOf: 'generated-review' })

    expect(fx.service.renameRun(fx.agent, run.runId, 'Review Run').displayName).toBe('Review Run')
    const savedPath = await fx.service.saveRun(fx.agent, run.runId, 'review-copy', 'personal')
    expect(savedPath).toMatch(/review-copy\.workflow\.json$/u)
    await fx.service.renameSaved(fx.agent, 'review-copy', 'review-renamed', 'personal')
    expect((await fx.service.load(fx.agent, 'review-renamed')).capsule?.manifest.name).toBe('review-renamed')

    const rerun = await fx.service.rerun(fx.agent, run.runId, { request: 'src' }, undefined, true)
    expect(await rerun.done).toMatchObject({ status: 'completed', resumedFromRunId: run.runId })
    expect(fx.service.runs(fx.agent).length).toBeGreaterThanOrEqual(2)
    expect(fx.service.attachBackgroundJob(fx.agent, rerun)).toBe('workflow-1')
    expect(fx.jobs.start).toHaveBeenCalledOnce()

    await fx.service.deleteSaved(fx.agent, 'review-renamed', 'personal')
    fx.service.deleteRun(fx.agent, run.runId)
    expect(fx.service.show(fx.agent, run.runId)).toBeUndefined()
    expect(fx.service.prune(fx.agent, { keep: 0, dryRun: true }).candidates).toBeDefined()
  })

  it('requires one explicit confirmation per trusted-local execution and preserves target ambiguity', async () => {
    const fx = await fixture()
    const trusted = join(fx.root, 'project-workflows', 'trusted.mjs')
    await mkdir(join(fx.root, 'project-workflows'), { recursive: true })
    await writeFile(trusted, `export default { meta: { name: 'trusted', description: 'trusted local', phases: ['run'], readOnly: true, maxAgents: 1, maxConcurrency: 1, patterns: ['classify-and-act'] }, run: async () => 'trusted-ok' }`)
    const first = await fx.service.startNamed(fx.agent, 'trusted')
    expect(await first.done).toMatchObject({ status: 'completed', result: 'trusted-ok' })
    expect(fx.userQuestions.ask).toHaveBeenCalledTimes(1)
    await expect(fx.service.rerun(fx.agent, 'trusted', {}, undefined, false)).rejects.toThrow(/ambiguous between a run and saved workflow/u)
    const second = await fx.service.startNamed(fx.agent, 'trusted')
    expect(await second.done).toMatchObject({ status: 'completed', result: 'trusted-ok' })
    expect(fx.userQuestions.ask).toHaveBeenCalledTimes(2)
  })

  it('revises saved generated workflows through scout-author repair', async () => {
    const fx = await fixture()
    await fx.service.create(fx.agent, 'review this', new AbortController().signal, { scope: 'project' })
    const revised = await fx.service.revise(fx.agent, 'generated-review', 'make it stricter', new AbortController().signal, true)
    expect(revised.path).toMatch(/generated-review\.workflow\.json$/u)
    expect(revised.capsule.provenance).toMatchObject({ revisionOf: 'generated-review' })
  })

  it('fails loud on ambiguous/missing reruns and exposes optional background and confirmation seams', async () => {
    const fx = await fixture()
    await expect(fx.service.rerun(fx.agent, 'missing', {})).rejects.toThrow(/was not found/u)
    fx.userQuestions.ask.mockResolvedValueOnce({ answers: [{ id: 'workflow-approval', selected: ['Cancel'] }] })
    expect(await fx.service.confirm(fx.agent, 'Run?', 'detail')).toBe(false)

    let jobSpec: { run(): { cancel(reason: string): void; done: Promise<{ status: string }> } } | undefined
    const capturingJobs = { start: vi.fn((input: NonNullable<typeof jobSpec>) => { jobSpec = input; return 'background-id' }) }
    const withJobs = new DynamicWorkflowService(new Context(), { config: config(fx.root), subagents: fx.fake.value, jobs: capturingJobs as never })
    expect(withJobs.attachBackgroundJob(fx.agent, completedRun('stopped'))).toBe('background-id')
    const stoppedControl = jobSpec!.run()
    expect(await stoppedControl.done).toMatchObject({ status: 'killed' })
    stoppedControl.cancel('cancel again')
    withJobs.attachBackgroundJob(fx.agent, completedRun('failed'))
    expect(await jobSpec!.run().done).toMatchObject({ status: 'failed' })

    const minimal = new DynamicWorkflowService(new Context(), { config: config(fx.root), subagents: fx.fake.value })
    const verification = { preflight: vi.fn(async () => []), verify: vi.fn(async () => []) }
    const isolation = { name: 'test', prepare: vi.fn(async () => ({ cwd: fx.root, parent: fx.agent, dispose: vi.fn(async () => {}) })) }
    const dispatch = { start: vi.fn(async ({ provider, request, subagents: runtime }) => await runtime.start(provider, request)) }
    const removeVerification = minimal.registerVerificationAdapter(verification)
    expect(() => minimal.registerVerificationAdapter(verification)).toThrow(/already registered/u)
    removeVerification()
    const removeIsolation = minimal.registerIsolationAdapter(isolation)
    expect(() => minimal.registerIsolationAdapter(isolation)).toThrow(/already registered/u)
    removeIsolation()
    const removeDispatch = minimal.registerDispatchAdapter(dispatch)
    expect(() => minimal.registerDispatchAdapter(dispatch)).toThrow(/already registered/u)
    removeDispatch()
    expect(minimal.attachBackgroundJob(fx.agent, completedRun('completed'))).toBeUndefined()
    await expect(minimal.confirm(fx.agent, 'Run?', 'detail')).rejects.toThrow(/user-questions provider/u)
    const trustedModule = {
      manifest: validateWorkflowManifest({ name: 'function-only', description: 'No generated source.', phases: ['run'], readOnly: true, maxAgents: 1, maxConcurrency: 1, patterns: ['classify-and-act'] }),
      execution: 'trusted-package' as const,
      run: async () => 'function-result',
    }
    expect(await (await minimal.startInline(fx.agent, trustedModule)).done).toMatchObject({ status: 'completed', result: 'function-result' })
    expect(() => minimal.registerVerificationAdapter(verification)).toThrow(/before the first workflow operation/u)
    expect(() => minimal.registerIsolationAdapter(isolation)).toThrow(/before the first workflow operation/u)
    expect(() => minimal.registerDispatchAdapter(dispatch)).toThrow(/before the first workflow operation/u)
    await expect(minimal.saveRun(fx.agent, 'run-completed', 'nope', 'project')).rejects.toThrow(/no generated capsule snapshot/u)
  })
})
